#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 8001
  
#mybatis配置文件
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml #mybatis的sql的mapper接口映射文件
  type-aliases-package: cn.sgz.springcloud.entity #对应实体类的路径
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名转换

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql;
  
spring:
  profiles: dev # 开发环境
  application:
    name: microservice-product-config # ******服务名*******
    #数据源配置
  datasource:
    username: test
    password: 2pB88mUiHI9Z$uZ0
    url: jdbc:mysql://210.72.13.99:3306/sanfront
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource #指定自定义的数据源类型,如果这里不指定,默认使用的是HikariDataSource
    initialSize: 8 #数据库连接池初始化连接大小
    minIdle: 5 #数据库连接池最小连接池数量
    maxActive: 20 #数据库连接池最大连接池数量
    maxWait: 60000 #获取连接时最大等待时间，单位毫秒
    timeBetweenEvictionRunsMillis: 60000 #有两个含义：1) Destroy线程会检测连接的间隔时间，即配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 2) testWhileIdle的判断依据；
    minEvictableIdleTimeMillis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 FROM DUAL #用来检测连接是否有效的sql
    testWhileIdle: true #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testOnBorrow: false #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnReturn: false #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    poolPreparedStatements: false #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭,分库分表较多的数据库，建议配置为false。
    maxPoolPreparedStatementPerConnectionSize: -1 #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
    #监控配置
    filters: stat,wall,slf4j
    useGlobalDataSourceStat: true #合并多个DruidDataSource的监控数据，多数据源
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500 #druid.stat.mergeSql=true 合并执行的相同sql，避免因为参数不同而统计多条sql语句, druid.stat.slowSqlMillis=500 用来配置SQL慢的标准，执行时间超过slowSqlMillis的就是慢

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true
---
server:
  port: 8001
  
#mybatis配置文件
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml #mybatis的sql的mapper接口映射文件
  type-aliases-package: cn.sgz.springcloud.entity #对应实体类的路径
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名转换

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql;
  
spring:
  profiles: dev # 开发环境
  application:
    name: microservice-product-config # ******服务名*******
    #数据源配置
  datasource:
    username: test
    password: 2pB88mUiHI9Z$uZ0
    url: jdbc:mysql://210.72.13.99:3306/yewuxitong
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource #指定自定义的数据源类型,如果这里不指定,默认使用的是HikariDataSource
    initialSize: 8 #数据库连接池初始化连接大小
    minIdle: 5 #数据库连接池最小连接池数量
    maxActive: 20 #数据库连接池最大连接池数量
    maxWait: 60000 #获取连接时最大等待时间，单位毫秒
    timeBetweenEvictionRunsMillis: 60000 #有两个含义：1) Destroy线程会检测连接的间隔时间，即配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 2) testWhileIdle的判断依据；
    minEvictableIdleTimeMillis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 FROM DUAL #用来检测连接是否有效的sql
    testWhileIdle: true #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testOnBorrow: false #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnReturn: false #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    poolPreparedStatements: false #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭,分库分表较多的数据库，建议配置为false。
    maxPoolPreparedStatementPerConnectionSize: -1 #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
    #监控配置
    filters: stat,wall,slf4j
    useGlobalDataSourceStat: true #合并多个DruidDataSource的监控数据，多数据源
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500 #druid.stat.mergeSql=true 合并执行的相同sql，避免因为参数不同而统计多条sql语句, druid.stat.slowSqlMillis=500 用来配置SQL慢的标准，执行时间超过slowSqlMillis的就是慢

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true